allowBuilds:
  esbuild: true
  sharp: true
overrides:
  '@opentelemetry/core': ^2.8.0
  fast-uri: ^3.1.5
  postcss: ^8.5.23
  yaml: ^2.8.3
minimumReleaseAgeExclude:
  - '@astrojs/internal-helpers@0.10.1'
  - '@astrojs/markdown-satteri@0.3.3'
  - astro@7.0.6
